import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Box, Toolbar, Typography } from '@mui/material'
import React from 'react';
import Portret from 'public/images/portret.jpg'
import WelcomeSectionCss from 'styles/WelcomeSection.module.css'
import LocationOnIcon from '@mui/icons-material/LocationOn';

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar sx={{
        gap: { xs: '12px', sm: '38px' }, justifyContent: 'center', alignItems: 'center',
        flex: 0.2, flexDirection: { xs: 'column-reverse', sm: 'row' }, borderBottom: '3px solid #fff'
      }}>
        <div style={{ display: 'flex', flexDirection: 'column', flex: 0.4 }}>
          <Typography
            noWrap
            style={{ fontSize: "100px", textAlign: 'center' }}
            component="span"
            className="caltonBoldGlowWhite"
          >
            Lashes
          </Typography>
          <Typography
            noWrap
            style={{ fontSize: "48px", textAlign: 'center' }}
            component="span"
          >
            by Kaja
          </Typography>
        </div>
        <Image src={Portret.src} height={280} width={280} alt="portret" className={WelcomeSectionCss.image} />
      </Toolbar>
      <Toolbar sx={{position: 'relative', top: '-30px', justifyContent: 'center', gap: '12px'}}>
        <LocationOnIcon fontSize="small" sx={{color:'white', fontSize: '32px'}}/>
        <Typography
          style={{ fontSize: "32px", textAlign: 'center', alignItems: 'center', justifyContent: 'center' }}
          component="span"
        >
          Sokolska Ulica 45, Maribor
        </Typography>
      </Toolbar >
    </>
  )
}
