import Container from '@/components/container/container';
import Head from 'next/head'
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Allocade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'flex', flex: 0.5 }}>
        <Container></Container>
      </div>
    </>
  )
}
